name: llm-tools
channels:
  - pytorch
  - nvidia
  - conda-forge
  - xformers
  - defaults
dependencies:
  - python=3.12
  - pydantic>=2.7.3
  - pydantic-settings>=2.3.1
  - pre-commit>=3.7.1
  - ruff>=0.4.8
  - transformers>=4.41.2
  - pandas>=2.2.2
  - accelerate>=0.31.0
  - pytorch=2.4.0
  - pytorch-cuda>=12.4
  - cuda
  - openai
  # - xformers
  - pytest>=8.2.2
  - peft 
  - evaluate
  # - flash-attn>=2.5.8
  - pip:
      - ray>=2.31.0
      - vllm
      - rouge_score
    # - "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
