name: llm-tools
channels:
  - pytorch
  - nvidia
  - conda-forge
  - xformers
  - defaults
dependencies:
  - python>=3.11
  - pillow>=9.4.0
  - pandas>=2.2.3
  - pytorch>=2.5.*
  - torchvision=0.20.1
  - pytorch-cuda>=12.4
  - cuda
  - pydantic>=2.7.3
  - pydantic-settings>=2.3.1
  - pre-commit>=3.7.1
  - ruff>=0.4.8
  - transformers>=4.41.2
  - accelerate>=0.31.0
  - openai>=1.5.2
  - pyarrow>=16.1.0
  # - xformers
  - pytest>=8.2.2
  - peft>=0.13.2
  - evaluate>=0.4.1
  - wandb >= 0.18.7
  # - flash-attn>=2.5.8
  - pip:
      - vllm
      - bitsandbytes
      - rouge_score
      - "unsloth @ git+https://github.com/unslothai/unsloth.git"
      - "unsloth_zoo @ git+https://github.com/unslothai/unsloth-zoo.git"
