name: llm-inference
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
  - xformers
dependencies:
  - python=3.12
  - pydantic>=2.7.3
  - pydantic-settings>=2.3.1
  - pre-commit>=3.7.1
  - ruff>=0.4.8
  - transformers>=4.41.2
  - pandas>=2.2.2
  - accelerate>=0.31.0
  - pytorch=2.3.0
  - pytorch-cuda>=12.1
  - cuda
  - openai
  - xformers
  - pytest>=8.2.2
  # - flash-attn>=2.5.8
  - pip:
      - ray>=2.31.0
    # - vllm==0.4.3
    # - "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
