[project]
name = "llm-inference"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Artem Durynin", email = "artem5542@gmail.com" }
]
dependencies = [
    "pydantic>=2.7.3",
    "pydantic-settings>=2.3.1",
    "pre-commit>=3.7.1",
    "ruff>=0.4.8",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/llm_inference"]
